# Generated by Django 4.0.1 on 2022-04-19 11:25

from django.db import migrations, models
import trademanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators_configuration', models.JSONField(default=trademanagement.models.default_indicators_configuration)),
                ('configurations', models.JSONField(blank=True, default=dict, null=True)),
                ('storage', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('trade_management_configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('trade_management_class', models.CharField(choices=[('SampleTradeManagement', 'SampleTradeManagement'), ('Alpha', 'Alpha')], max_length=200)),
            ],
            options={
                'verbose_name': 'Trade Management',
                'verbose_name_plural': 'Trade Managements',
            },
        ),
    ]
