# Generated by Django 4.0.1 on 2022-05-15 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trademanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators_configuration', models.JSONField(blank=True, default=trademanagement.models.default_indicators_configuration, null=True)),
                ('configurations', models.JSONField(blank=True, default=dict, null=True)),
                ('storage', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('trade_management_configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('trade_management_class', models.CharField(choices=[('SampleTradeManagement', 'SampleTradeManagement'), ('Alpha', 'Alpha')], max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_trademanagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Management',
                'verbose_name_plural': 'Trade Managements',
            },
        ),
    ]
