# Generated by Django 4.0.1 on 2022-05-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import strategy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators_configuration', models.JSONField(blank=True, default=strategy.models.default_indicators_configuration, null=True)),
                ('configurations', models.JSONField(blank=True, default=dict, null=True)),
                ('strategy_class', models.CharField(choices=[('SampleStrategy', 'SampleStrategy'), ('Alpha', 'Alpha')], max_length=200)),
                ('storage', models.JSONField(blank=True, default=dict, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
    ]
