# Generated by Django 4.0.1 on 2022-01-19 11:17

from django.db import migrations, models
import strategy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators_configuration', models.JSONField(default=strategy.models.default_indicators_configuration)),
                ('strategy_configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('strategy_class', models.CharField(choices=[('SampleStrategy', 'SampleStrategy')], max_length=200)),
                ('strategy_storage', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
    ]
