# Generated by Django 4.0.1 on 2022-05-09 11:42

from django.db import migrations, models
import strategy.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='indicators_configuration',
            field=models.JSONField(blank=True, default=strategy.models.default_indicators_configuration, null=True),
        ),
    ]
