# Generated by Django 4.0.1 on 2022-01-21 10:53

from django.db import migrations, models
import strategy.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='symbol_timeframe_pair',
            field=models.JSONField(default=strategy.models.default_symbol_timeframe_pair),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_class',
            field=models.CharField(choices=[('SampleStrategy', 'SampleStrategy'), ('TradingSystem', 'TradingSystem')], max_length=200),
        ),
    ]
