# Generated by Django 4.0.1 on 2022-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_rename_strategy_configuration_strategy_configurations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategy_class',
            field=models.CharField(choices=[('SampleStrategy', 'SampleStrategy'), ('Alpha', 'Alpha')], max_length=200),
        ),
    ]
