# Generated by Django 4.0.1 on 2022-04-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskmanagement', '0001_initial'),
        ('strategy', '0005_rename_strategy_configuration_strategy_configurations_and_more'),
        ('broker', '0011_broker_buying_power'),
        ('trademanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol_timeframe_pair', models.JSONField(default=dict)),
                ('configurations', models.JSONField(default=dict)),
                ('storage', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_brokers', to='broker.broker')),
                ('risk_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_risk_managements', to='riskmanagement.riskmanagement')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_strategies', to='strategy.strategy')),
                ('trade_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_trade_managements', to='trademanagement.trademanagement')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
    ]
