# Generated by Django 4.0.1 on 2022-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_system_configurations_alter_system_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='symbol_timeframe_pair',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
