# Generated by Django 4.0.1 on 2022-01-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Sybmol',
                'verbose_name_plural': 'Sybmols',
            },
        ),
        migrations.CreateModel(
            name='TimeframeAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Timeframe alias',
                'verbose_name_plural': 'Timeframe aliases',
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('alias_id', models.ManyToManyField(related_name='timeframe_other_name', to='data.TimeframeAlias')),
            ],
            options={
                'verbose_name': 'Timeframe',
                'verbose_name_plural': 'Timeframes',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('open_bid', models.FloatField()),
                ('close_bid', models.FloatField()),
                ('high_bid', models.FloatField()),
                ('low_bid', models.FloatField()),
                ('open_ask', models.FloatField(blank=True, null=True)),
                ('close_ask', models.FloatField(blank=True, null=True)),
                ('high_ask', models.FloatField(blank=True, null=True)),
                ('low_ask', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_symbol', to='data.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_timeframe', to='data.timeframe')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'unique_together': {('datetime', 'timeframe', 'symbol')},
            },
        ),
    ]
