# Generated by Django 4.0.1 on 2022-01-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_ibddatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibddatafile',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
