# Generated by Django 4.0.1 on 2022-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibddata',
            name='after_hours_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='after_hours_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='analyst_recom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='average_true_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='average_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='change_from_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_growth_next_5_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_growth_next_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_growth_past_5_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_growth_quarter_over_quarter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_growth_this_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='eps_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='finviz_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='float_short',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='forward_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='gross_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='high_50_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='high_52_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='insider_ownership',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='insider_transactions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='institutional_ownership',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='institutional_transactions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='ipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='low_50_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='low_52_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='lt_debt_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='operating_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='p_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='p_free_cash_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='payout_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='peg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_half_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_quarter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='performance_ytd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='ps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='quick_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='relative_strength_index_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='relative_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='return_on_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='return_on_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='return_on_investment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='sales_growth_past_5_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='sales_growth_quarter_over_quarter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='share_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='shares_outstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='short_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='simple_moving_average_200_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='simple_moving_average_20_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='simple_moving_average_50_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='total_debt_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='volatility_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='volatility_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddata',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
