# Generated by Django 4.0.1 on 2022-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_ibddata_after_hours_change_ibddata_after_hours_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinvizDataFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ibd_data_files')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finviz data file',
                'verbose_name_plural': 'Finviz data files',
            },
        ),
    ]
