# Generated by Django 4.0.1 on 2022-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_after_hours_change_ibddata_after_hours_change_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibddata',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ibddata',
            name='price_change_in_currency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ibddata',
            name='price_change_in_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
