# Generated by Django 4.0.1 on 2022-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_ibddata_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvizdatafile',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddatafile',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
