# Generated by Django 4.0.1 on 2022-01-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_finvizdatafile_data_date_ibddatafile_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibddata',
            name='acc_dis_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ibddata',
            name='ind_grp_rs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ibddata',
            name='smr_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ibddata',
            name='spon_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
