# Generated by Django 4.0.1 on 2022-01-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_ibddata_acc_dis_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvizdatafile',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finvizdatafile',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ibddatafile',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddatafile',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
