# Generated by Django 4.0.1 on 2022-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_finvizdatafile_errors_finvizdatafile_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvizdatafile',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibddatafile',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
