# Generated by Django 4.0.1 on 2022-01-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_finvizdatafile_processed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finvizdatafile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ibddatafile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
