# Generated by Django 4.0.1 on 2022-01-30 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_ibddata_acc_dis_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ibddata',
            options={'verbose_name': 'Stock data', 'verbose_name_plural': 'Stock data'},
        ),
        migrations.AlterField(
            model_name='finvizdatafile',
            name='data_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ibddatafile',
            name='data_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
