# Generated by Django 4.0.1 on 2022-01-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_ibddata_options_alter_finvizdatafile_data_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvizdatafile',
            name='creator',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
        ),
    ]
