# Generated by Django 4.0.1 on 2022-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_finvizdatafile_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvizdatafile',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ibddatafile',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
