# Generated by Django 4.0.1 on 2022-02-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_finvizdatafile_is_processing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinvizSectorDataFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('file', models.FileField(upload_to='finviz_sector_data_files')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data_date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Finviz sector data file',
                'verbose_name_plural': 'Finviz sector data files',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='FinvizSectorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('market_cap', models.FloatField(blank=True, default=None, null=True)),
                ('pe', models.FloatField(blank=True, default=None, null=True)),
                ('forward_pe', models.FloatField(blank=True, default=None, null=True)),
                ('peg', models.FloatField(blank=True, default=None, null=True)),
                ('ps', models.FloatField(blank=True, default=None, null=True)),
                ('pb', models.FloatField(blank=True, default=None, null=True)),
                ('pc', models.FloatField(blank=True, default=None, null=True)),
                ('p_free_cash_flow', models.FloatField(blank=True, default=None, null=True)),
                ('dividend_yield_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('eps_growth_past_5_years_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('eps_growth_next_5_years_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('sales_growth_past_5_years_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('float_short_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_week_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_month_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_quarter_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_half_year_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_year_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('performance_year_to_date_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('analyst_recom', models.FloatField(blank=True, default=None, null=True)),
                ('average_volume', models.FloatField(blank=True, default=None, null=True)),
                ('relative_volume', models.FloatField(blank=True, default=None, null=True)),
                ('change_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('volume', models.FloatField(blank=True, default=None, null=True)),
                ('stocks', models.FloatField(blank=True, default=None, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finviz_sector_data', to='data.sector')),
            ],
            options={
                'verbose_name': 'Finviz sector data',
                'verbose_name_plural': 'Finviz sector data',
                'unique_together': {('date', 'sector')},
            },
        ),
    ]
