# Generated by Django 4.0.1 on 2022-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_finvizsectordatafile_sector_finvizsectordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
