# Generated by Django 4.0.1 on 2022-02-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_sector_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinvizInsiderDataFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('file', models.FileField(upload_to='finviz_insider_data_files')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data_date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Finviz insider data file',
                'verbose_name_plural': 'Finviz insider data files',
            },
        ),
        migrations.CreateModel(
            name='FinvizInsiderData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('date', models.DateField()),
                ('owner', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('transaction', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Option Exercise', 'Option Exercise')], default=None, max_length=200, null=True)),
                ('cost', models.FloatField(blank=True, default=None, null=True)),
                ('shares', models.FloatField(blank=True, default=None, null=True)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
                ('shares_total', models.FloatField(blank=True, default=None, null=True)),
                ('sec_form_4', models.DateTimeField(blank=True, default=None, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finviz_insider_data', to='data.symbol')),
            ],
            options={
                'verbose_name': 'Finviz insider data',
                'verbose_name_plural': 'Finviz insider data',
                'unique_together': {('date', 'symbol', 'sec_form_4', 'owner')},
            },
        ),
    ]
