# Generated by Django 4.0.1 on 2022-02-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0022_alter_finvizinsiderdata_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=10)),
                ('trade_datetime', models.DateTimeField()),
                ('broker', models.CharField(choices=[('InteractiveBrokers', 'InteractiveBrokers'), ('FakeBroker', 'FakeBroker')], max_length=20)),
                ('position_id', models.CharField(max_length=200)),
                ('position_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10)),
                ('trade_price', models.FloatField()),
                ('trade_size', models.FloatField()),
                ('trade_stop_loss', models.FloatField(blank=True, null=True)),
                ('trade_limit', models.FloatField(blank=True, null=True)),
                ('executor', models.CharField(max_length=200)),
                ('parent_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_trades', to='trade.trade')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='data.symbol')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
    ]
