# Generated by Django 4.0.1 on 2022-02-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_broker_broker_class_delete_trade'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_trades', to='broker.broker'),
        ),
    ]
