# Generated by Django 4.0.1 on 2022-05-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_price_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='main_quanity',
            new_name='main_quantity',
        ),
    ]
