# Generated by Django 4.0.1 on 2022-02-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trade_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='sent_arguments',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Placed', 'Placed'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=10),
        ),
    ]
