# Generated by Django 4.0.1 on 2022-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_trade_error_trade_sent_arguments_trade_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='sent_arguments',
            field=models.JSONField(default=dict),
        ),
    ]
