# Generated by Django 4.0.1 on 2022-02-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_sent_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
