# Generated by Django 4.0.1 on 2022-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
