# Generated by Django 4.0.1 on 2022-02-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_trade_quantity_alter_trade_trade_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='position_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
