# Generated by Django 4.0.1 on 2022-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_alter_trade_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='place_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PendingSubmit', 'PendingSubmit'), ('PendingCancel', 'PendingCancel'), ('PreSubmitted', 'PreSubmitted'), ('Cancelled', 'Cancelled'), ('Submitted', 'Submitted'), ('Filled', 'Filled'), ('Inactive', 'Inactive'), ('Failed', 'Failed')], default='PendingSubmit', max_length=50),
        ),
    ]
