# Generated by Django 4.0.1 on 2022-03-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategy_symbol_timeframe_pair_and_more'),
        ('trade', '0011_remove_trade_executor_trade_is_executed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategy_trades', to='strategy.strategy'),
        ),
    ]
