# Generated by Django 4.0.1 on 2022-05-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_class', models.CharField(choices=[('InteractiveBrokers', 'InteractiveBrokers'), ('FakeBroker', 'FakeBroker')], max_length=50)),
                ('storage', models.JSONField(blank=True, default=dict, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('buying_power', models.FloatField(default=0.0)),
                ('used_margin', models.FloatField(default=0.0)),
                ('connected', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_broker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
    ]
