# Generated by Django 4.0.1 on 2022-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_api_key_broker_password_broker_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], default='USD', max_length=50),
            preserve_default=False,
        ),
    ]
