# Generated by Django 4.0.1 on 2022-02-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broker', '0002_rename_closed_datetime_trade_trade_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('broker_class', models.CharField(choices=[('FakeBroker', 'FakeBroker')], max_length=50)),
                ('storage', models.JSONField(default=dict)),
                ('balance', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('used_maring', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_broker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
        migrations.DeleteModel(
            name='BrokerStorage',
        ),
    ]
