# Generated by Django 4.0.1 on 2022-02-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_broker_delete_brokerstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_class',
            field=models.CharField(choices=[('InteractiveBrokers', 'InteractiveBrokers'), ('FakeBroker', 'FakeBroker')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
