# Generated by Django 4.0.1 on 2022-02-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_broker_broker_class_delete_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='used_maring',
            new_name='used_margin',
        ),
    ]
