# Generated by Django 4.0.1 on 2022-02-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_rename_used_maring_broker_used_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_size', models.FloatField(blank=True, null=True)),
                ('position_stop_loss', models.FloatField(blank=True, null=True)),
                ('position_limit', models.FloatField(blank=True, null=True)),
                ('position_type', models.CharField(blank=True, max_length=200, null=True)),
                ('trade_datetime', models.DateTimeField(blank=True, null=True)),
                ('trade_price', models.FloatField(blank=True, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=200, null=True)),
                ('position_id', models.CharField(blank=True, max_length=200, null=True)),
                ('executor', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
