# Generated by Django 4.0.1 on 2022-02-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_delete_openposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
