# Generated by Django 4.0.1 on 2022-02-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_broker_connected_broker_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='storage',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
