# Generated by Django 4.0.1 on 2022-02-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_alter_broker_public_key_alter_broker_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
