# Generated by Django 4.0.1 on 2022-03-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_broker_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='buying_power',
            field=models.FloatField(default=0.0),
        ),
    ]
