# Generated by Django 4.0.1 on 2022-05-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsi',
            fields=[
                ('sub_indicator_configuration', models.JSONField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('value', models.FloatField()),
                ('avg_gain', models.FloatField()),
                ('avg_loss', models.FloatField()),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsi', to='data.data')),
            ],
            options={
                'unique_together': {('period', 'price_id')},
            },
        ),
        migrations.CreateModel(
            name='Divergence',
            fields=[
                ('sub_indicator_configuration', models.JSONField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('value', models.FloatField()),
                ('slope_price', models.FloatField()),
                ('slope_rsi', models.FloatField()),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergence', to='data.data')),
            ],
            options={
                'unique_together': {('period', 'price_id')},
            },
        ),
    ]
