# Generated by Django 4.0.1 on 2022-05-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_finvizinsiderdata_transaction'),
        ('indicator', '0002_rsimodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RsiModel',
            new_name='Rsi',
        ),
        migrations.CreateModel(
            name='Divergence',
            fields=[
                ('sub_indicator_configuration', models.JSONField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('value', models.FloatField()),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergence', to='data.data')),
            ],
            options={
                'unique_together': {('period', 'price_id')},
            },
        ),
    ]
