# Generated by Django 4.0.1 on 2022-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_rename_rsimodel_rsi_divergence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='divergence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='divergence',
            name='slope_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divergence',
            name='slope_rsi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsi',
            name='avg_gain',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsi',
            name='avg_loss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
