# Generated by Django 4.0.1 on 2022-04-19 11:25

from django.db import migrations, models
import riskmanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators_configuration', models.JSONField(default=riskmanagement.models.default_indicators_configuration)),
                ('allowed_trading_capital', models.FloatField(default=0.0)),
                ('risk', models.FloatField(default=0.0)),
                ('max_capital_allocation_per_trade_percent', models.FloatField(default=0.0)),
                ('configurations', models.JSONField(blank=True, default=dict, null=True)),
                ('storage', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('risk_management_configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('risk_management_class', models.CharField(choices=[('SampleRiskManagement', 'SampleRiskManagement'), ('Alpha', 'Alpha')], max_length=200)),
            ],
            options={
                'verbose_name': 'Risk Management',
                'verbose_name_plural': 'Risk Managements',
            },
        ),
    ]
