# Generated by Django 4.0.1 on 2022-05-09 11:45

from django.db import migrations, models
import riskmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='indicators_configuration',
            field=models.JSONField(blank=True, default=riskmanagement.models.default_indicators_configuration, null=True),
        ),
    ]
