# Generated by Django 4.0.1 on 2022-05-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0002_alter_riskmanagement_indicators_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskmanagement',
            old_name='allowed_trading_capital',
            new_name='allowed_trading_capital_percent',
        ),
        migrations.RenameField(
            model_name='riskmanagement',
            old_name='risk',
            new_name='risk_percent',
        ),
    ]
