# Generated by Django 4.0.1 on 2022-01-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbdData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('price_change_in_currency', models.FloatField()),
                ('price_change_in_percentage', models.FloatField()),
                ('comp_rating', models.FloatField(blank=True, null=True)),
                ('eps_rating', models.FloatField(blank=True, null=True)),
                ('industry_group_rank', models.FloatField(blank=True, null=True)),
                ('rs_rating', models.FloatField(blank=True, null=True)),
                ('ind_grp_rs', models.CharField(max_length=10)),
                ('smr_rating', models.CharField(max_length=10)),
                ('acc_dis_rating', models.CharField(max_length=10)),
                ('spon_rating', models.CharField(max_length=10)),
                ('vol_change_in_percentage', models.FloatField(blank=True, null=True)),
                ('vol_change_in_1k_s', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibd_data', to='data.symbol')),
            ],
            options={
                'verbose_name': 'IBD data',
                'verbose_name_plural': 'IBD data',
                'unique_together': {('date', 'symbol')},
            },
        ),
    ]
