# Generated by Django 4.0.1 on 2022-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_ibddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbdDataFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ibd_data_files')),
            ],
            options={
                'verbose_name': 'IBD data file',
                'verbose_name_plural': 'IBD data files',
            },
        ),
    ]
