# Generated by Django 4.0.1 on 2022-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_ibddatafile_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
