# Generated by Django 4.0.1 on 2022-01-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broker', models.CharField(choices=[('FakeBroker', 'FakeBroker')], max_length=20)),
                ('storage', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Broker Storage',
                'verbose_name_plural': 'Broker Storages',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opened_datetime', models.DateTimeField()),
                ('closed_datetime', models.DateTimeField()),
                ('broker', models.CharField(choices=[('FakeBroker', 'FakeBroker')], max_length=20)),
                ('position_id', models.CharField(max_length=200)),
                ('position_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10)),
                ('opened_price', models.FloatField()),
                ('closed_price', models.FloatField(blank=True, null=True)),
                ('position_size', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='data.symbol')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
    ]
