# Generated by Django 4.0.1 on 2022-01-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='closed_datetime',
            new_name='trade_datetime',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='closed_price',
            new_name='trade_limit',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='opened_price',
            new_name='trade_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='position_size',
            new_name='trade_size',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='opened_datetime',
        ),
        migrations.AddField(
            model_name='trade',
            name='executor',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='parent_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_trades', to='broker.trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=10),
            preserve_default=False,
        ),
    ]
