# Generated by Django 4.0.1 on 2022-05-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('enable_broker_scheduled_calls', models.BooleanField(default=False)),
                ('enable_finviz', models.BooleanField(default=False)),
                ('enable_systems', models.BooleanField(default=False)),
                ('loop_wait', models.IntegerField(default=60)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('pid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Runner',
                'verbose_name_plural': 'Runner',
            },
        ),
    ]
