# Generated by Django 4.0.1 on 2022-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('enable_finviz', models.BooleanField(default=False)),
                ('enable_strategies', models.BooleanField(default=False)),
                ('look_wait', models.IntegerField(default=60)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Runner',
                'verbose_name_plural': 'Runner',
            },
        ),
    ]
