# Generated by Django 4.0.1 on 2022-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_rename_look_wait_runnerstatus_loop_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerstatus',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
