# Generated by Django 4.0.1 on 2022-02-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_runnerstatus_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerstatus',
            name='enable_broker_scheduled_calls',
            field=models.BooleanField(default=False),
        ),
    ]
