# Generated by Django 4.0.1 on 2022-04-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_runnerstatus_enable_broker_scheduled_calls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runnerstatus',
            old_name='enable_strategies',
            new_name='enable_systems',
        ),
    ]
