# Generated by Django 4.0.1 on 2023-07-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodels',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
