# Generated by Django 4.0.1 on 2023-07-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_finvizinsiderdata_created_at_datetime_and_more'),
        ('ml', '0003_alter_mlmodels_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodels',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='data.symbol'),
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='model_type',
            field=models.CharField(blank=True, choices=[('RandomForestClassifier', 'Randomforestclassifier'), ('LogisticRegression', 'Logisticregression'), ('NeuralNetwork', 'Neuralnetwork'), ('XgBoost', 'Xgboost'), ('DecisionTree', 'Decisiontree')], max_length=50, null=True),
        ),
    ]
